debug: false

spring:
  profiles:
    active: local
  application:
    name: jpa-${spring.profiles}
  datasource:
    url: jdbc:postgresql://localhost:5432/crom?currentSchema=${spring.profiles}
    hikari:
      driver-class-name: org.postgresql.Driver
      username: crom
      password: qwe123
      pool-name: ${spring.application.name}-pool
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
        use_sql_comments : true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true

---
spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: create-drop
---
spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
